services:
  - type: web
    name: taskable
    runtime: python
    buildCommand: bash build.sh
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT --proxy-headers
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
